AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Description: 'AWS CloudFormation Template for ecr public repo'
Parameters:
  repositoryName:
    Type: String

Resources:
  EcrRepo: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Ref repositoryName
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPull
            Effect: Allow
            Principal: 
              AWS: 
                - "*"
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
Outputs:    
  Arn:
    Value: !GetAtt EcrRepo.Arn