AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Description: 'AWS CloudFormation Sample Template RDS_MySQL_With_Read_Replica create a highly-available, RDS DBInstance with a read replica.'
Parameters:
  dBName:
    Default: ''
    Description: The database name
    Type: String
  dBUser:
    NoEcho: 'true'
    Description: The database admin account username
    Default: ''
    Type: String
  dBPassword:
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    Default: ''
  dBAllocatedStorage:
    Default: '20'
    Description: The size of the database (Gb)
    Type: Number
  storageType: 
    Default: "gp2"
    Type: String
    AllowedValues: [gp2, io1, st1]
  dBInstanceClass:
    Description: The database instance type
    Type: String
    Default: db.t2.small
  dBSnapshotIdentifier:
    Description: 'Optional identifier for the DB cluster snapshot from which you want to restore (leave blank to create an empty cluster).'
    Type: String
    Default: ''
  dBInstanceIdentifier:
    Description: The database instance ID
    Type: String
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  publiclyAccessible:
    Description: Publicly accessible parameter for BD
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    ConstraintDescription: must be true or false.
  multiAZ:
    Description: Multi-AZ master database
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']
    ConstraintDescription: must be true or false.
  vpcId:
    Type: String
    Description: Enter your VPCID
  publicSubnet1:
    Type: String
  publicSubnet2:
    Type: String
  engineVersion:
    Type: String
    Default: '8.0.11'
    Description: Select your engine version for MYSQL
    AllowedValues: [5.5.61, 5.5.59, 5.5.57, 5.5.54, 5.5.53, 5.5.46, 5.6.34, 5.6.35, 5.6.37, 5.6.39, 5.6.40, 5.6.41, 5.7.16, 5.7.17, 5.7.19, 5.7.21, 5.7.22, 5.7.23, 8.0.11]

Conditions:
  HasDBSnapshotIdentifier: !Not [!Equals [!Ref dBSnapshotIdentifier, '']]

Resources:
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      VpcId: !Ref 'vpcId'
      GroupDescription: Access to database
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 3306
          ToPort: 3306
          IpProtocol: tcp
      Tags: 
        - Key: Name
          Value: !Sub ${dBName}-security-group
  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: CloudFormation managed DB subnet group.
      SubnetIds:
        - !Ref publicSubnet1
        - !Ref publicSubnet2
  MasterDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref 'dBName'
      AllocatedStorage: !Ref 'dBAllocatedStorage'
      DBInstanceClass: !Ref 'dBInstanceClass'
      DBSnapshotIdentifier: !If [HasDBSnapshotIdentifier, !Ref dBSnapshotIdentifier, !Ref 'AWS::NoValue']
      DBInstanceIdentifier: !Ref 'dBInstanceIdentifier'
      PubliclyAccessible: !Ref 'publiclyAccessible'
      StorageType: !Ref storageType
      Engine: MySQL
      EngineVersion: !Ref engineVersion
      MasterUsername: !If [HasDBSnapshotIdentifier, !Ref 'AWS::NoValue', !Ref dBUser]
      MasterUserPassword: !If [HasDBSnapshotIdentifier, !Ref 'AWS::NoValue', !Ref dBPassword]
      MultiAZ: !Ref 'multiAZ'
      Tags:
      - Key: Name
        Value: Master Database
      DBSubnetGroupName:
        Ref: DatabaseSubnetGroup
      VPCSecurityGroups:
        - Ref: DatabaseSecurityGroup
    DeletionPolicy: Snapshot

Outputs:
  MasterJDBCConnectionString:
    Description: JDBC connection string for the master database
    Value: !Join ['', ['jdbc:mysql://', !GetAtt [MasterDB, Endpoint.Address], ':',
        !GetAtt [MasterDB, Endpoint.Port], /, !Ref 'dBName']]