AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a AWS Batch environment, includes IAM resources and Batch resources.
Parameters:
  memory:
    Type: String
    Description: The hard limit (in MiB) of memory to present to the container. If your container attempts to exceed the memory specified here, the container is killed.
    Default: 200
  
  vcpus:
    Type: String
    Description: The number of vCPUs reserved for the container.
    Default: 1

  image:
    Type: String
    Description: The image used to start a container.
    Default: jesus10/helloworld:latest

  jobDefinitionName:
    Type: String
    Description: The image used to start a container.
    Default: default


Resources:
  BatchTaskRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ${AWS::StackName}-task-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - 
            Effect: 'Allow'
            Principal:
              Service:
                - 'ecs-tasks.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
  
  ScheduleBatch:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      ContainerProperties:
        Image: !Ref image
        Vcpus: !Ref vcpus
        Memory: !Ref memory
        JobRoleArn: !Ref BatchTaskRole
      JobDefinitionName: !Ref jobDefinitionName
      RetryStrategy:
        Attempts: 1

Outputs:
  ScheduleBatch:
    Value: !Ref 'ScheduleBatch'

