AWSTemplateFormatVersion: "2010-09-09"
Description: Policy set 

Resources:
  BasePowerUsersPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: 'PowerUsers' #Name group of users
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: BatchReadOnlyPower
            Effect: Allow
            Action: 
              - batch:Describe*
              - batch:List*
              - batch:SubmitJob
            Resource: '*'
          -
            Sid: ECSReadOnlyPower
            Effect: Allow
            Action: 
              - ecs:Describe*
              - ecs:List*
            Resource: '*'
          -
            Sid: CodeCommitAllowAllPower
            Effect: Allow
            Action: 
              - codecommit:Get*
              - codecommit:List*
              - codecommit:CreateCommit
              - codecommit:CreateBranch
              - codecommit:CreatePullRequest
              - codecommit:CreateUnreferencedMergeCommit
              - codecommit:BatchGet*
              - codecommit:Describe*
              - codecommit:Put*
              - codecommit:Post*
              - codecommit:Merge*
              - codecommit:TestRepositoryTriggers
              - codecommit:UpdateComment
              - codecommit:UpdatePullRequestDescription
              - codecommit:UpdatePullRequestStatus
              - codecommit:UpdatePullRequestTitle
              - codecommit:GitPull
              - codecommit:GitPush
            Resource: '*'
          - 
            Sid: CodeCommitDeletePower
            Effect: Allow
            Action:
              - codecommit:DeleteBranch
            Resource: '*'
            Condition:
              StringNotEquals:
                codecommit:References:
                  - refs/heads/master
                  - refs/heads/stage
                  - refs/heads/mobi-stage
          -
            Sid: SSMReadOnlyAllPower
            Effect: Allow
            Action: 
              - ssm:DescribeParameters
            Resource: '*'
          -
            Sid: SSMFullAccessNotDeletePower
            Effect: Allow
            Action:
              - ssm:PutParameter
              - ssm:GetParameterHistory
              - ssm:GetParametersByPath
              - ssm:GetParameters
              - ssm:GetParameter
            Resource: '*'
          -
            Sid: FullAccesToDevSqs
            Effect: Allow
            Action: 
              - sqs:*
            Resource: !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:dev-*'
          -
            Sid: KmsReadDecryptPower
            Effect: Allow
            Action:
              - kms:GenerateDataKey
              - kms:Decrypt
              - kms:ListAliases
            Resource: '*'
          - 
            Sid: ReadAccesToAllSqsPower
            Effect: Allow
            Action:
              - cloudwatch:GetMetricStatistics
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:ListDeadLetterSourceQueues
              - sqs:ListQueues
            Resource: '*'
          -
            Sid: S3ReadWriteObjAccessButNotDeletePower
            Effect: Allow
            Action:
              - s3:AbortMultipartUpload
              # - s3:DeleteObject
              - s3:DeleteObjectTagging
              - s3:DeleteObjectVersion
              - s3:DeleteObjectVersionTagging
              - s3:Get*
              - s3:ListMultipartUploadParts
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:PutObjectTagging
              - s3:PutObjectVersionAcl
              - s3:PutObjectVersionTagging
              - s3:RestoreObject
              - s3:List*
            Resource: '*'
          -
            Sid: ReadAccessToCWLogs
            Effect: Allow
            Action: 
              - logs:Describe*
              - logs:Get*
              - logs:List*
              - logs:TestMetricFilter
              - logs:FilterLogEvents
            Resource: '*'
          -
            Sid: CreateDevLogsGroup
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:PutRetentionPolicy
            Resource: '*'
          - 
            Sid: WriteStream
            Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogStreams
              - logs:GetLogEvents
            Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:dev:log-stream:*'
          - 
            Sid: ReadAccessToLambda
            Effect: Allow
            Action:
              - lambda:GetAccountSettings
              - lambda:ListFunctions
              - lambda:ListTags
              - lambda:GetEventSourceMapping
              - lambda:ListEventSourceMappings
              - iam:ListRoles
            Resource: '*'
          - 
            Sid: ReadAccessToApiGateway
            Effect: Allow
            Action:
              - apigateway:GET
              - execute-api:Invoke
            Resource: '*'
          - 
            Sid: ReadAccessToRdsInsights
            Effect: Allow
            Action: 
              - pi:DescribeDimensionKeys
              - pi:GetResourceMetrics
            Resource: 'arn:aws:pi:*:*:metrics/rds/*'


  BaseMidUsersPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: 'MidUsers' #Name group of users
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: PipeLineReadOnlyMid
            Effect: Allow
            Action: 
              - codepipeline:GetPipeline
              - codepipeline:GetPipelineState
              - codepipeline:GetPipelineExecution
              - codepipeline:ListPipelineExecutions
              - codepipeline:ListActionTypes
              - codepipeline:ListPipelines
            Resource: '*'
          -
            Sid: BatchReadOnlyMid
            Effect: Allow
            Action: 
              - batch:Describe*
              - batch:List*
            Resource: '*'
          -
            Sid: ECSReadOnlyMid
            Effect: Allow
            Action: 
              - ecs:Describe*
              - ecs:List*
            Resource: '*'
          -
            Sid: FullAccesToDevSqsMid
            Effect: Allow
            Action: 
              - sqs:*
            Resource: !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:dev-*'
          -
            Sid: KmsReadDecryptMid
            Effect: Allow
            Action:
              - kms:GenerateDataKey
              - kms:Decrypt
              - kms:ListAliases
            Resource: '*'
          - 
            Sid: ReadAccesToAllSqsMid
            Effect: Allow
            Action:
              - cloudwatch:GetMetricStatistics
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:ListDeadLetterSourceQueues
              - sqs:ListQueues
            Resource: '*'
          -
            Sid: S3ReadWriteObjAccessButNotDeleteMidd
            Effect: Allow
            Action:
              - s3:AbortMultipartUpload
              # - s3:DeleteObject
              - s3:DeleteObjectTagging
              - s3:DeleteObjectVersion  
              - s3:DeleteObjectVersionTagging
              - s3:Get*
              - s3:ListMultipartUploadParts
              - s3:PutObject  
              - s3:PutObjectAcl 
              - s3:PutObjectTagging
              - s3:PutObjectVersionAcl  
              - s3:PutObjectVersionTagging
              - s3:RestoreObject
              - s3:List*
            Resource: '*'
          -
            Sid: ReadAccessToCWLogs
            Effect: Allow
            Action: 
              - logs:Describe*
              - logs:Get*
              - logs:List*
              - logs:TestMetricFilter
              - logs:FilterLogEvents
            Resource: '*'
          -
            Sid: CreateDevLogsGroup
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:PutRetentionPolicy
            Resource: '*'
          - 
            Sid: WriteStream
            Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogStreams
              - logs:GetLogEvents
            Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:dev:log-stream:*'
          -
            Sid: CodeCommitAllowAllMid
            Effect: Allow
            Action: 
              - codecommit:Get*
              - codecommit:List*
              - codecommit:CreateBranch
              - codecommit:CreatePullRequest
              - codecommit:CreateUnreferencedMergeCommit
              - codecommit:BatchGet*
              - codecommit:Describe*
              - codecommit:PutRepositoryTriggers
              - codecommit:Post*
              - codecommit:TestRepositoryTriggers
              - codecommit:UpdateComment
              - codecommit:UpdatePullRequestDescription
              - codecommit:UpdatePullRequestStatus
              - codecommit:UpdatePullRequestTitle
              - codecommit:GitPull
            Resource: '*'
          - 
            Sid: CodeCommitDenyMasterMid
            Effect: Allow
            Action:
              - codecommit:CreateCommit
              - codecommit:GitPush
              - codecommit:PutFile
              - codecommit:Merge*
              - codecommit:DeleteBranch
            Resource: '*'
            Condition:
              StringNotEquals:
                codecommit:References:
                  - refs/heads/master
                  - refs/heads/mobi-stage

  BaseMobileUsersPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: 'MobileUsers' #Name group of users
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: CodeCommitAllowAllMobile
            Effect: Allow
            Action: 
              - codecommit:CreateBranch
              - codecommit:CreateRepository
              - codecommit:CreateCommit
              - codecommit:CreatePullRequest
              - codecommit:CreateUnreferencedMergeCommit
              - codecommit:Describe*
              - codecommit:Post*
              - codecommit:TestRepositoryTriggers
              - codecommit:UpdateComment
              - codecommit:UpdatePullRequestDescription
              - codecommit:UpdatePullRequestStatus
              - codecommit:UpdatePullRequestTitle
              - codecommit:GitPull
              - codecommit:GitPush
              - codecommit:Merge*
              - codecommit:Put*
              - codecommit:BatchGet*
              - codecommit:Get* 
            Resource: 'arn:aws:codecommit:eu-west-1:278900400641:mobile-*'
          -
            Sid: CodeCommitReadOnlyallMobile
            Effect: Allow
            Action: 
              - codecommit:List*
            Resource: '*'
          - 
            Sid: CodeCommitDeleteMobile
            Effect: Allow
            Action:
              - codecommit:DeleteBranch
            Resource: '*'
            Condition:
              StringNotEquals:
                codecommit:References:
                  - refs/heads/master