AWSTemplateFormatVersion: '2010-09-09'
Description: VPC Peer Routing
Parameters:
  VpcPeerConnectionId:
    Type: String
    Description: VPC Peer Connection ID
    AllowedPattern: ^pcx-[a-f0-9]{17}$
    ConstraintDescription: Valid VPC Peer Connection Id
  PeerVpcCidr:
    Type: String
    Description: VPC Peer CIDR
    AllowedPattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$
    ConstraintDescription: Valid CIDR
  LocalRouteTableId:
    Type: String
    Description: Local VPC Route Table ID
Outputs: {}
Resources:
  PeerVpcRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref 'PeerVpcCidr'
      RouteTableId: !Ref 'LocalRouteTableId'
      VpcPeeringConnectionId: !Ref 'VpcPeerConnectionId'
